Algoritmo "Lista 03 Questão 03"
//Prof: Aldo
//Faça um algoritmo que calcula e escreve a seguinte soma:
//soma = 1/1 + 3/2 + 5/3 + 7/4 + ... + 99/50

Var
   x,y:inteiro
   soma: real


Inicio
   x<-1
   y<-1

   para Y de Y ate 50 passo 1 faca

      Soma <- Soma + (X/Y)

      escreval("Soma:",x,"/",y)
      X<- X+2


   fimpara

   escreval ("A soma dos números é:",soma)


Fimalgoritmo