Algoritmo "Lista 03 Questão 04"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Aldo
//Escreva um algoritmo que gera números entre 1000 e 1999 e mostra
//aqueles que divididos por 11 dão resto 5"
Var
   Num: inteiro


Inicio
   para num de 1000 ate 1999 passo 1 faca
      se (num mod 11 = 5) entao
         escreval (num, " dividido por 11 dá resto 5!")
      fimse
   fimpara

Fimalgoritmo